### ISSUE TITLE
Doesn't build with `vector < 0.13`

### ISSUE THREAD

**Issue by lehins** [sergv/vector-quicksort#3]
Looks like this package relies on new unboxing helpers from `vector`, which didn't become available till the latest released version:
```
vector-quicksort             > /tmp/stack-650a082afd521c26/vector-quicksort-0.1/src-predefined/Data/Vector/Algorithms/Quicksort/Predefined/Pair.hs:26:10: error:
vector-quicksort             >     Not in scope: type constructor or class ‘U.IsoUnbox’
vector-quicksort             >     Perhaps you meant ‘U.Unbox’ (imported from Data.Vector.Unboxed)
vector-quicksort             >     Module ‘Data.Vector.Unboxed’ does not export ‘IsoUnbox’.
vector-quicksort             >    |
vector-quicksort             > 26 | instance U.IsoUnbox (TestPair a b) (a, b) where
...
```

**Comment by sergv** [comment]
Thanks, I made new hackage revision. For the record the library itself should work with earlier vectors, it's the tests that require 0.13 or higher.
